INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (325, 954, 'Cleaned everything, even my mess.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (284, 530, 'Everything was fine until they tried to steal my boyfriend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (753, 33, 'Outstanding service! Highly recommend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (933, 938, 'Fine, but stole my food a few times, wouldn''t admit it.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (583, 795, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (592, 125, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (25, 227, 'Had to call the police due to hostility.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (446, 382, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (811, 620, 'Everything was fine until they tried to steal my boyfriend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (483, 587, 'Very very cluttered and always playing crazy video games.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (797, 931, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (468, 900, 'Cooks the worst smelling food in the entire world.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (698, 568, 'Their friends will be over allllll the time, so be prepared', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (297, 538, 'Very very cluttered and always playing crazy video games.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (251, 499, 'Takes really long showers.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (36, 599, 'I love love love them.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (839, 312, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (984, 960, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (1000, 309, 'Fine, but stole my food a few times, wouldn''t admit it.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (895, 537, 'Good roomie, except for the one time she crashed out over a situationship and broke my mom''s portrait.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (81, 359, 'Fine, but stole my food a few times, wouldn''t admit it.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (694, 293, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (208, 239, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (431, 224, 'Outstanding service! Highly recommend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (684, 997, 'Neither great nor terrible.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (887, 746, 'Met basic expectations.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (883, 817, 'They''re great, just use bleach like it''s the bible. Prepare to pass out sometimes.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (956, 674, 'Very very cluttered and always playing crazy video games.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (321, 653, 'Had to call the police due to hostility.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (486, 240, 'Neither great nor terrible.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (223, 477, 'Takes really long showers.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (132, 285, 'Had a party everynight and tried to sell my furniture.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (250, 128, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (345, 46, 'Terrible roommate; would not recommend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (528, 147, 'Her cat thought my litter was her close.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (163, 154, 'Cooks the worst smelling food in the entire world.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (452, 40, 'They definitely sent me the edited pictures of the room.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (959, 589, 'Neither great nor terrible.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (277, 57, 'Below average experience overall.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (909, 42, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (456, 82, '10/10 person, even bailed me out of jail once.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (942, 737, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (267, 930, 'They''re great, just use bleach like it''s the bible. Prepare to pass out sometimes.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (625, 805, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (98, 707, 'Everything was fine until they tried to steal my boyfriend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (999, 110, 'Very very cluttered and always playing crazy video games.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (352, 728, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (383, 181, 'Very very cluttered and always playing crazy video games.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (225, 95, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (699, 223, 'I love love love them.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (233, 663, '10/10 person, even bailed me out of jail once.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (955, 625, 'Had a party everynight and tried to sell my furniture.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (533, 705, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (427, 446, 'Everything was fine until they tried to steal my boyfriend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (725, 802, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (489, 29, 'Fine, but stole my food a few times, wouldn''t admit it.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (49, 68, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (640, 41, 'Clean, quiet, and a geat friend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (900, 773, 'Very disappointed with the how inconsiderate they were.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (984, 568, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (757, 834, 'They''re great, just use bleach like it''s the bible. Prepare to pass out sometimes.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (779, 844, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (146, 919, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (749, 912, 'Good roomie, except for the one time she crashed out over a situationship and broke my mom''s portrait.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (463, 722, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (7, 644, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (511, 399, 'Below average experience overall.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (411, 186, 'Very disappointed with the how inconsiderate they were.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (778, 154, 'Cooks the worst smelling food in the entire world.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (990, 853, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (23, 604, 'I love love love them.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (829, 431, 'I love love love them.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (125, 392, 'I would use this again.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (43, 532, 'Lazy.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (821, 491, 'Neither great nor terrible.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (661, 376, '10/10 person, even bailed me out of jail once.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (794, 283, 'Had to call the police due to hostility.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (73, 556, 'Had to call the police due to hostility.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (481, 275, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (555, 310, '10/10 person, even bailed me out of jail once.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (915, 670, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (821, 768, 'Very very cluttered and always playing crazy video games.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (829, 437, 'Met basic expectations.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (328, 788, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (878, 34, 'Outstanding service! Highly recommend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (284, 741, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (232, 445, 'Her cat thought my litter was her close.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (662, 413, 'Had to call the police due to hostility.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (513, 636, 'Cleaned everything, even my mess.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (942, 881, 'Were paired as randoms, now one of my closest friends.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (732, 569, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (38, 39, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (509, 168, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (739, 958, 'Lazy.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (97, 180, 'Very very cluttered and always playing crazy video games.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (314, 297, 'Fine, but stole my food a few times, wouldn''t admit it.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (453, 889, 'Their friends will be over allllll the time, so be prepared', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (634, 682, 'Quite satisfied with the service.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (531, 370, 'They''re great, just use bleach like it''s the bible. Prepare to pass out sometimes.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (91, 340, 'Everything was fine until they tried to steal my boyfriend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (966, 980, 'Very disappointed with the how inconsiderate they were.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (850, 487, 'Met basic expectations.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (949, 41, 'Had to call the police due to hostility.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (162, 713, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (835, 809, 'Cooks the worst smelling food in the entire world.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (716, 849, 'Clean, quiet, and a geat friend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (810, 983, 'Had to call the police due to hostility.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (535, 915, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (895, 727, 'I would use this again.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (169, 199, 'Clean, quiet, and a geat friend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (989, 77, 'Below average experience overall.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (446, 147, 'Takes really long showers.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (624, 726, 'Were paired as randoms, now one of my closest friends.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (81, 561, 'Their friends will be over allllll the time, so be prepared', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (727, 494, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (788, 921, 'Their friends will be over allllll the time, so be prepared', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (598, 393, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (116, 360, 'Met basic expectations.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (588, 596, 'Fine, but stole my food a few times, wouldn''t admit it.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (534, 639, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (327, 791, 'Cooks the worst smelling food in the entire world.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (524, 670, 'Below average experience overall.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (869, 725, 'They definitely sent me the edited pictures of the room.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (870, 106, 'Her cat thought my litter was her close.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (285, 284, 'Takes really long showers.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (780, 965, 'Neither great nor terrible.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (666, 904, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (406, 841, '10/10 person, even bailed me out of jail once.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (693, 564, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (830, 418, 'Cleaned everything, even my mess.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (692, 984, 'Had a party everynight and tried to sell my furniture.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (304, 430, 'Had a party everynight and tried to sell my furniture.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (916, 259, 'Neither great nor terrible.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (132, 750, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (786, 587, 'Met basic expectations.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (784, 274, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (525, 595, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (560, 913, 'Terrible roommate; would not recommend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (83, 583, 'Lazy.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (211, 288, 'Outstanding service! Highly recommend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (419, 420, 'Fine, but stole my food a few times, wouldn''t admit it.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (449, 500, 'I would use this again.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (545, 133, 'Fine, but stole my food a few times, wouldn''t admit it.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (409, 819, 'Their friends will be over allllll the time, so be prepared', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (59, 863, 'Outstanding service! Highly recommend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (268, 630, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (784, 762, 'Good roomie, except for the one time she crashed out over a situationship and broke my mom''s portrait.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (234, 346, 'Everything was fine until they tried to steal my boyfriend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (414, 91, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (164, 460, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (890, 82, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (791, 571, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (700, 198, 'Were paired as randoms, now one of my closest friends.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (758, 787, 'Her cat thought my litter was her close.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (237, 350, 'Terrible roommate; would not recommend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (994, 273, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (740, 683, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (367, 634, 'Terrible roommate; would not recommend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (956, 807, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (454, 449, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (132, 264, 'Lazy.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (571, 345, 'Quite satisfied with the service.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (814, 295, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (754, 620, 'Had a party everynight and tried to sell my furniture.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (126, 555, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (426, 988, 'Had to call the police due to hostility.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (460, 265, 'Fine, but stole my food a few times, wouldn''t admit it.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (448, 278, 'Below average experience overall.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (417, 368, 'Her cat thought my litter was her close.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (883, 523, '10/10 person, even bailed me out of jail once.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (220, 36, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (846, 252, 'Terrible roommate; would not recommend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (713, 459, 'They definitely sent me the edited pictures of the room.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (596, 807, 'Met basic expectations.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (914, 752, 'Clean, quiet, and a geat friend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (105, 826, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (676, 666, 'Quite satisfied with the service.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (192, 531, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (961, 111, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (389, 161, 'I would use this again.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (451, 271, 'Had to call the police due to hostility.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (214, 188, 'They''re great, just use bleach like it''s the bible. Prepare to pass out sometimes.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (122, 439, 'I would use this again.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (906, 648, 'I love love love them.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (616, 982, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (427, 67, 'They definitely sent me the edited pictures of the room.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (385, 306, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (157, 851, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (201, 95, 'Takes really long showers.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (684, 566, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (568, 229, 'Met basic expectations.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (41, 777, 'Their friends will be over allllll the time, so be prepared', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (781, 373, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (341, 623, 'They definitely sent me the edited pictures of the room.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (232, 430, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (910, 50, 'Cleaned everything, even my mess.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (343, 932, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (406, 571, 'Neither great nor terrible.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (197, 889, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (983, 247, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (315, 347, 'Everything was fine until they tried to steal my boyfriend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (889, 124, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (859, 928, 'They''re great, just use bleach like it''s the bible. Prepare to pass out sometimes.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (728, 9, 'They definitely sent me the edited pictures of the room.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (520, 437, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (563, 694, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (849, 544, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (322, 524, 'Clean, quiet, and a geat friend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (258, 145, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (368, 951, 'Clean, quiet, and a geat friend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (820, 835, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (772, 512, 'Met basic expectations.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (278, 626, 'Were paired as randoms, now one of my closest friends.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (455, 856, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (837, 969, 'Had to call the police due to hostility.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (235, 21, 'Were paired as randoms, now one of my closest friends.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (664, 860, 'Were paired as randoms, now one of my closest friends.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (421, 646, 'Cooks the worst smelling food in the entire world.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (129, 44, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (431, 870, 'Had a party everynight and tried to sell my furniture.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (898, 594, 'Clean, quiet, and a geat friend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (347, 648, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (94, 231, 'Met basic expectations.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (461, 49, 'Terrible roommate; would not recommend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (432, 217, 'Takes really long showers.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (60, 277, 'I love love love them.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (157, 851, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (406, 137, 'They definitely sent me the edited pictures of the room.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (808, 26, 'Good roomie, except for the one time she crashed out over a situationship and broke my mom''s portrait.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (617, 307, 'Everything was fine until they tried to steal my boyfriend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (826, 704, 'Lazy.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (288, 494, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (322, 727, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (528, 423, 'Her cat thought my litter was her close.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (754, 948, 'Everything was fine until they tried to steal my boyfriend.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (573, 766, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (101, 219, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (120, 238, 'Quite satisfied with the service.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (699, 551, 'Good roomie, except for the one time she crashed out over a situationship and broke my mom''s portrait.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (13, 484, 'I would use this again.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (441, 997, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (320, 262, 'Quite satisfied with the service.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (856, 316, 'Neither great nor terrible.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (168, 454, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (637, 731, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (820, 978, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (438, 506, 'Cooks the worst smelling food in the entire world.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (338, 194, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (161, 907, 'They''re great, just use bleach like it''s the bible. Prepare to pass out sometimes.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (907, 809, 'Quite satisfied with the service.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (453, 34, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (95, 847, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (746, 606, 'Cooks the worst smelling food in the entire world.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (87, 453, 'Outstanding service! Highly recommend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (108, 407, 'It was okay; some aspects were average.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (180, 714, 'Below average experience overall.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (847, 1, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (554, 982, 'I love love love them.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (537, 651, 'Very disappointed with the how inconsiderate they were.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (167, 195, 'Cleaned everything, even my mess.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (194, 517, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (937, 355, '10/10 person, even bailed me out of jail once.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (217, 531, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (59, 877, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (200, 409, 'Their friends will be over allllll the time, so be prepared', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (428, 857, 'Not very impressed; room for improvement.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (876, 180, 'Good roomie, except for the one time she crashed out over a situationship and broke my mom''s portrait.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (254, 698, 'Cleaned everything, even my mess.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (866, 851, 'Good roomie, except for the one time she crashed out over a situationship and broke my mom''s portrait.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (156, 784, 'Great roommate, just lowkey (highkey) a liar.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (910, 891, 'Cooks the worst smelling food in the entire world.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (202, 756, 'Fine, but stole my food a few times, wouldn''t admit it.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (474, 871, 'Good roomie, except for the one time she crashed out over a situationship and broke my mom''s portrait.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (779, 726, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (235, 270, 'I would use this again.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (270, 426, 'Their friends will be over allllll the time, so be prepared', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (342, 146, 'Her cat thought my litter was her close.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (650, 236, 'Lazy.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (723, 637, 'Quite satisfied with the service.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (871, 293, 'Met basic expectations.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (422, 374, 'They''re great, just use bleach like it''s the bible. Prepare to pass out sometimes.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (193, 126, 'Were paired as randoms, now one of my closest friends.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (840, 858, '10/10 person, even bailed me out of jail once.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (178, 559, 'They paid the rent for the both of us, #rich.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (565, 335, 'They definitely sent me the edited pictures of the room.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (120, 414, '10/10 person, even bailed me out of jail once.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (787, 239, 'Very disappointed with the how inconsiderate they were.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (576, 18, 'Could have been better.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (819, 745, 'Clean, quiet, and a geat friend.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (291, 96, '10/10 person, even bailed me out of jail once.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (392, 315, 'Cleaned everything, even my mess.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (815, 773, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (652, 518, 'Very disappointed with the how inconsiderate they were.', 1);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (156, 955, 'Exceeded expectations in every way.', 5);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (439, 292, 'Only problem was they refused to clean the bathroom.', 3);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (572, 8, 'I would use this again.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (119, 432, 'They definitely sent me the edited pictures of the room.', 2);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (199, 673, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (376, 178, 'Very good experience overall.', 4);
INSERT INTO review (reviewerId, revieweeId, content, ratingValue) VALUES (165, 253, 'Cleaned everything, even my mess.', 5);
